### ISSUE TITLE
Things that don't translate between PHP and Go...

### ISSUE THREAD

**Issue by protosam** [arthurkushman/pgo#6]
As someone who has used php since 2002 and go since 2015 (and various other languages in between). There are some very inherient problems with this package that /r/golang pointed out on reddit: https://www.reddit.com/r/golang/comments/aax0ho/terrific_go_library_for_php_community_with/

The list of them and what's wrong...

https://github.com/arthurkushman/pgo/blob/master/core.go#L15 
https://github.com/arthurkushman/pgo/blob/master/pdate.go#L25
If you're writing a web app in go, you don't want your route to panic the entire application. This results in the site is down. Error handling does not translate between php and go. You have to just handle your errors.

https://github.com/arthurkushman/pgo/blob/master/pfiles.go#L23
You're not handling potential type errors that could arise if that isn't an integer.

https://github.com/arthurkushman/pgo/blob/master/pfiles.go#L28
What if your file contents aren't even long enough for this? 

https://github.com/arthurkushman/pgo/blob/master/pstr.go#L16
... variable name is variable type, rename that var... 

A lot of what you're doing is great for learning from a php background to get into golang, but I wouldn't run any of this in production.

**Comment by protosam** [comment]
@arthurkushman here's some of my thoughts, hopefully they help.

In regards to error handling, you're really just going to have to return all errors as type `error`, an additional value. For example:
```
import "errors"

...

func myfn(str string) (string, error) {
	if str == "hello" {
		return str, nil
	}
	return "", errors.New("Input to myfn(string) must be hello!")
}
```


Handling errors for inputs that are possibly not integers should probably be done like:
Ref: https://github.com/arthurkushman/pgo/blob/master/pfiles.go#L54-L56
```
if !okOff || !okLim {
	errmsg := fmt.Sprintf("Error on passing params with wrong types to FileGetContents: offset %T and limit %T", args[1], args[2])
	return nil, errors.New(errmsg)
}
```

Having a variable name matching the name of a datatype in any language leads to confusion, especially when it comes to new people maintaining your code later. I still recommend renaming it, because as-is it would only make detailed code documentation confusing or even confuse someone reading through the code that's fresh into the language coming from another language. It's regarded as bad style.

Whenever you run your `printError()` function it still has very bad side effects: https://github.com/arthurkushman/pgo/blob/master/core.go#L26-L28
Consider that your application should never exit, if it's supposed to be a web server using the http library. If someone just forgets to handle some input somewhere and an error occurs in many of your functions, `os.Exit(1)` will close the entire program and the developer of that web app is left with a down website where only 1 small feature may have just been broken for a night.

In PHP where it's fine for you to `die()` whenever, because script execution runs only once per page load.

In contrast when you write web apps in Go, Ruby, Python, etc. you're making a daemon that continually runs. `die()` are not good for these use cases. Any API or library assuming that it should be doing process level stuff that could immediately stop an application is really bad in these scenarios and should only return errors for the developer to handle in his own code.

**Comment by arthurkushman** [comment]
I've done as much as I could while finding time between pjs, if there will be any proposals - will be glad to move forward with better dev practices. Thx
